# Generated by Django 4.0.6 on 2022-07-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_app', '0002_alter_fileupload_options_fileupload_date_upload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='date_upload_file',
            field=models.DateTimeField(),
        ),
    ]
