# Generated by Django 4.0.6 on 2022-07-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_app', '0003_alter_fileupload_date_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='date_upload_file',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
